; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = https://github.com/platformio/platform-espressif32.git
framework = arduino
board = esp32doit-devkit-v1
monitor_speed = 115200
lib_deps = 
	hideakitai/ArduinoEigen@^0.2.3
	https://github.com/14chanwa/Adafruit_VL53L0X
	fastled/FastLED@^3.9.3
	adafruit/Adafruit VL53L1X@^3.1.2
	matthieuvigne/STS_Servos@^1.2.1
	robtillaart/CRC@^1.0.4
build_type = release
build_flags = 
	-D CONFIG_ARDUHAL_LOG_COLORS
	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
board_build.f_cpu = 240000000L
monitor_raw = yes
upload_protocol = espota
upload_port = 42.42.0.152