#ifndef _ROBOT_STATE_HPP
#define _ROBOT_STATE_HPP


enum RobotState
{
    WAIT_FOR_CONFIGURATION,
    WAIT_FOR_MATCH_START,
    MOVING_SETUP_TRAJECTORY,
    MATCH_STARTED_WAITING,
    MATCH_STARTED_ACTION,
    MATCH_STARTED_FINAL_APPROACH,
    MATCH_ENDED
};

#endif